### ISSUE TITLE
HMMER_domainTblParser error

### ISSUE THREAD

**Issue by jameswoods22** [hallamlab/TreeSAPP#51] opened 2020-09-03 18:25 UTC
hi there, i'm running treesapp on some metagenome .faa files via the singularity install.

my input is: 

singularity exec treesapp_latest.sif treesapp assign -i /mydir/myfile.faa -o treesapp_test_output_2/ -m prot

while i had success with one of my .faa files, the second failed with this output:
"Searching for marker proteins in ORFs using hmmsearch.
[                                     ]-------------------------------------Parsing HMMER domain tables for high-quality matches... ERROR - HMMER_domainTblParser, line 185:
Unable to drop current HmmMatch from next_domain linked list.
-]" 
I'm not sure what I can do to avoid this error?
Thanks,
James

**Comment by cmorganl** [comment] 2020-09-03 19:51
Hi James,

Thanks for letting me know about this bug! It is definitely not caused by anything on your end, it's a rare bug caused by TreeSAPP not properly handling multiple HMM matches to the same query sequence.

I'm preparing a new release that will most likely fix this. I should have the next version released early next week. I'll let you know when it's ready.

Thanks,
Connor

**Comment by cmorganl** [comment] 2020-09-15 17:59
Hi James,

Sorry for the delay here. The new singularity container is available: https://cloud.sylabs.io/library/cmorganl/default/treesapp.

Let me know if you run into any problems!

Connor

**Comment by cmorganl** [comment] 2020-09-30 16:26
Closing this issue for now. Please re-open if it was not resolved!

**Closed by cmorganl** 2020-09-30 16:26 UTC
